//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleSolution.WPF.ExampleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDTO", Namespace="http://schemas.datacontract.org/2004/07/Example.DTO")]
    [System.SerializableAttribute()]
    public partial class EmployeeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OnBoardDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VacationDaysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OnBoardDate {
            get {
                return this.OnBoardDateField;
            }
            set {
                if ((this.OnBoardDateField.Equals(value) != true)) {
                    this.OnBoardDateField = value;
                    this.RaisePropertyChanged("OnBoardDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VacationDays {
            get {
                return this.VacationDaysField;
            }
            set {
                if ((this.VacationDaysField.Equals(value) != true)) {
                    this.VacationDaysField = value;
                    this.RaisePropertyChanged("VacationDays");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentDTO", Namespace="http://schemas.datacontract.org/2004/07/Example.DTO")]
    [System.SerializableAttribute()]
    public partial class DepartmentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExampleSolution.WPF.ExampleService.EmployeeDTO[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExampleSolution.WPF.ExampleService.EmployeeDTO[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExampleService.IExampleService")]
    public interface IExampleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/GetEmployeesByDepartment", ReplyAction="http://tempuri.org/IExampleService/GetEmployeesByDepartmentResponse")]
        ExampleSolution.WPF.ExampleService.EmployeeDTO[] GetEmployeesByDepartment(System.Guid departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/GetEmployeesByDepartment", ReplyAction="http://tempuri.org/IExampleService/GetEmployeesByDepartmentResponse")]
        System.Threading.Tasks.Task<ExampleSolution.WPF.ExampleService.EmployeeDTO[]> GetEmployeesByDepartmentAsync(System.Guid departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/CreateNewEmployee", ReplyAction="http://tempuri.org/IExampleService/CreateNewEmployeeResponse")]
        ExampleSolution.WPF.ExampleService.EmployeeDTO CreateNewEmployee(string firstName, string middleName, string lastName, decimal salary, System.Guid departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/CreateNewEmployee", ReplyAction="http://tempuri.org/IExampleService/CreateNewEmployeeResponse")]
        System.Threading.Tasks.Task<ExampleSolution.WPF.ExampleService.EmployeeDTO> CreateNewEmployeeAsync(string firstName, string middleName, string lastName, decimal salary, System.Guid departmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/CreateNewDepartment", ReplyAction="http://tempuri.org/IExampleService/CreateNewDepartmentResponse")]
        ExampleSolution.WPF.ExampleService.DepartmentDTO CreateNewDepartment(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/CreateNewDepartment", ReplyAction="http://tempuri.org/IExampleService/CreateNewDepartmentResponse")]
        System.Threading.Tasks.Task<ExampleSolution.WPF.ExampleService.DepartmentDTO> CreateNewDepartmentAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/GetDepartments", ReplyAction="http://tempuri.org/IExampleService/GetDepartmentsResponse")]
        ExampleSolution.WPF.ExampleService.DepartmentDTO[] GetDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/GetDepartments", ReplyAction="http://tempuri.org/IExampleService/GetDepartmentsResponse")]
        System.Threading.Tasks.Task<ExampleSolution.WPF.ExampleService.DepartmentDTO[]> GetDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/UpdateDepartment", ReplyAction="http://tempuri.org/IExampleService/UpdateDepartmentResponse")]
        ExampleSolution.WPF.ExampleService.DepartmentDTO UpdateDepartment(ExampleSolution.WPF.ExampleService.DepartmentDTO department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleService/UpdateDepartment", ReplyAction="http://tempuri.org/IExampleService/UpdateDepartmentResponse")]
        System.Threading.Tasks.Task<ExampleSolution.WPF.ExampleService.DepartmentDTO> UpdateDepartmentAsync(ExampleSolution.WPF.ExampleService.DepartmentDTO department);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExampleServiceChannel : ExampleSolution.WPF.ExampleService.IExampleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExampleServiceClient : System.ServiceModel.ClientBase<ExampleSolution.WPF.ExampleService.IExampleService>, ExampleSolution.WPF.ExampleService.IExampleService {
        
        public ExampleServiceClient() {
        }
        
        public ExampleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExampleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExampleSolution.WPF.ExampleService.EmployeeDTO[] GetEmployeesByDepartment(System.Guid departmentId) {
            return base.Channel.GetEmployeesByDepartment(departmentId);
        }
        
        public System.Threading.Tasks.Task<ExampleSolution.WPF.ExampleService.EmployeeDTO[]> GetEmployeesByDepartmentAsync(System.Guid departmentId) {
            return base.Channel.GetEmployeesByDepartmentAsync(departmentId);
        }
        
        public ExampleSolution.WPF.ExampleService.EmployeeDTO CreateNewEmployee(string firstName, string middleName, string lastName, decimal salary, System.Guid departmentId) {
            return base.Channel.CreateNewEmployee(firstName, middleName, lastName, salary, departmentId);
        }
        
        public System.Threading.Tasks.Task<ExampleSolution.WPF.ExampleService.EmployeeDTO> CreateNewEmployeeAsync(string firstName, string middleName, string lastName, decimal salary, System.Guid departmentId) {
            return base.Channel.CreateNewEmployeeAsync(firstName, middleName, lastName, salary, departmentId);
        }
        
        public ExampleSolution.WPF.ExampleService.DepartmentDTO CreateNewDepartment(string name) {
            return base.Channel.CreateNewDepartment(name);
        }
        
        public System.Threading.Tasks.Task<ExampleSolution.WPF.ExampleService.DepartmentDTO> CreateNewDepartmentAsync(string name) {
            return base.Channel.CreateNewDepartmentAsync(name);
        }
        
        public ExampleSolution.WPF.ExampleService.DepartmentDTO[] GetDepartments() {
            return base.Channel.GetDepartments();
        }
        
        public System.Threading.Tasks.Task<ExampleSolution.WPF.ExampleService.DepartmentDTO[]> GetDepartmentsAsync() {
            return base.Channel.GetDepartmentsAsync();
        }
        
        public ExampleSolution.WPF.ExampleService.DepartmentDTO UpdateDepartment(ExampleSolution.WPF.ExampleService.DepartmentDTO department) {
            return base.Channel.UpdateDepartment(department);
        }
        
        public System.Threading.Tasks.Task<ExampleSolution.WPF.ExampleService.DepartmentDTO> UpdateDepartmentAsync(ExampleSolution.WPF.ExampleService.DepartmentDTO department) {
            return base.Channel.UpdateDepartmentAsync(department);
        }
    }
}
